language: python
python:
  - "3.6"

os:
  - osx
  - linux

# command to install dependencies
install:
  - pip install -r requirements.txt

# operating specific installs
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pip install appscript          ; fi

# command to run tests
script:
  - pytest tests
